# Generated by Django 5.2.6 on 2025-09-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_service_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(editable=False)),
                ('source', models.CharField(choices=[('online', 'ออนไลน์'), ('walkin', 'หน้าร้าน')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('confirmed', 'ยืนยันแล้ว'), ('completed', 'เสร็จสิ้น'), ('canceled', 'ยกเลิก')], default='confirmed', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barber_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['barber', 'start_at'], name='bookings_bo_barber__7450be_idx')],
            },
        ),
    ]
